### ISSUE TITLE
[BUG] ng add trows error leading to incomplete installation

### ISSUE THREAD

**Issue by lazar0303** [vvaldersteins/ngx-svg#38] opened 2021-02-04 17:49 UTC
**Describe the bug**
Installation failed while using `ng add` in a new project.

**To Reproduce**
In CLI
```
$ ng new test
? Do you want to enforce stricter type checking and stricter bundle budgets in t
he workspace?
  This setting helps improve maintainability and catch bugs ahead of time.
  For more information, see https://angular.io/strict Yes
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
$ cd test
$ ng add @alyle/ui
? Set up HammerJS for gesture recognition? Yes
? What themes should be added? minima-light
UPDATE package.json (1278 bytes)
✔ Packages installed successfully.
Cannot find module '@schematics/angular/utility/config'
Require stack:
- /home/davidlazar/Documents/test/node_modules/@alyle/ui/schematics/ng-add/setup-project.js
- /home/davidlazar/Documents/test/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/davidlazar/Documents/test/node_modules/@angular-devkit/schematics/tools/index.js
- /home/davidlazar/Documents/test/node_modules/@angular/cli/utilities/json-schema.js
- /home/davidlazar/Documents/test/node_modules/@angular/cli/models/command-runner.js
- /home/davidlazar/Documents/test/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng

```

**Expected behavior**
No Error, updated app.module.ts, and probably some configs

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Fedora 33
 - Browser N/A
 - Version N/A

**Additional context**
```
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.1.2
Node: 14.15.4
OS: linux x64

Angular: 11.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   0.1101.2
@angular-devkit/core            11.1.2
@angular-devkit/schematics      11.1.2
@angular/cdk                    10.2.7
@schematics/angular             11.1.2
@schematics/update              0.1101.2
rxjs                            6.6.3
typescript                      4.1.3
    
```

**Comment by vvaldersteins** [comment] 2021-02-05 12:33
Hi! Thanks for informing. I was not able to reproduce the issue. Could you try following this guide on adding the library to your project - https://github.com/vvaldersteins/ngx-svg#installation ?

**Comment by vvaldersteins** [comment] 2021-02-16 11:37
Closing due to no reply.

**Closed as completed by vvaldersteins** 2021-02-16 11:37 UTC
Labels: bug
